added velocity loss
Rex109/D3D9-Hook-CoD4-Velometer pull request #2
Opened 2022-06-05 11:53 UTC by HaKaiiii

2022-06-05 12:12 UTC, Rex109 reviewed
I think there's a big issue with this... seems like it's triggering even if my velocity is perfectly stable and/or 0. plus i need you to leave the default ini settings to their default value and just add the new settings, other than this stuff it's a super-duper idea to add to the velometer!

2022-06-05 13:18 UTC, HaKaiiii commented
ahhh oki i can values to default but changing to velocityLoss color on consistent/stable speed was intended and dont you think it should work like that? 🤔

2022-06-05 13:30 UTC, HaKaiiii commented
I can make it not trigger on stable velocity if u want...
Just my opinion that velocity loss color on stable velocity would look cool

2022-06-05 14:28 UTC, Rex109 commented
> ahhh oki i can change values to default but changing to velocityLoss color on consistent/stable speed was intended and dont you think it should work like that? 🤔

Honestly i've never seen something like that, maybe i'm wrong but then it will beome a velocity gain color change instead of velocity loss

2022-06-05 14:31 UTC, HaKaiiii commented
yea in codjumper atleast that's how it usually works. Stable velocity and 0 is velocity loss color
i can just rename velocity color to velocity gain color and then should be good ^^

2022-06-06 13:19 UTC, Rex109 requested changes
Seems good now... the only thing i would ask you before merging is to fix the indention of some of the code, after that i'll give it a test and i'll let you know if i'll merge it or not.

2022-06-06 13:19 UTC, Rex109 commented on iw3velometer/dllmain.cpp
> +	ini.SetValue("Config", "velocityLossCheck", iw3velometerConfig.velocityLossCheck ? "True" : "False");
Here

2022-06-06 13:19 UTC, Rex109 commented on iw3velometer/dllmain.cpp
> +
Here

2022-06-06 13:19 UTC, Rex109 commented on iw3velometer/dllmain.cpp
> +	else if (showHud && !accel && iw3velometerConfig.velocityLossCheck)
Here

2022-06-06 13:19 UTC, Rex109 commented on iw3velometer/dllmain.cpp
> +		ImGui::DragInt("Velocity loss delay", &iw3velometerConfig.loss_velocity);
Here

2022-06-06 13:19 UTC, Rex109 commented on iw3velometer/dllmain.cpp
> +		ImGui::Checkbox("Show velocity loss", &iw3velometerConfig.velocityLossCheck);
Here

2022-06-06 13:19 UTC, Rex109 commented on iw3velometer/dllmain.cpp
> +	int loss_velocity = 30;
Here

2022-06-08 12:54 UTC, Rex109 approved these changes
Perfect! I'll merge the changes!

2022-06-08 12:55 UTC, Rex109 commented
And thanks for the font crash fix <3

2022-06-08 12:55 UTC, merged